In [30]:
from datetime import datetime
from datetime import timedelta
import pandas as pd
import matplotlib
import numpy as np

In [2]:
df=pd.read_pickle('data/2to9data.pkl')

In [3]:
df_short=df.copy()

In [4]:
df_short

,time,user,item
4347024,2010-06-29 18:44:26,11011110111110011001100100010011,梁静茹豪华婚礼实录.mp4
4347643,2010-06-29 19:00:39,11011110111110011001100100010011,传奇故事-100125-女研究生自杀之谜.mp4
4347646,2010-06-29 19:00:39,11011110111110011001100100010011,传奇故事-100125-女研究生自杀之谜.mp4
4347666,2010-06-29 19:01:01,11011110111110011001100100010011,传奇故事-100126-一场没有骗子的骗局.mp4
4347667,2010-06-29 19:01:03,11011110111110011001100100010011,传奇故事-100126-一场没有骗子的骗局.mp4
...,...,...,...
6959522,2010-07-01 12:57:36,00101111100110100100010010101101,新三国(第92集).mp4
7188472,2010-07-01 14:29:01,00101111100110100100010010101101,新三国(第93集).mp4
7206340,2010-07-01 16:09:47,00101111100110100100010010101101,新三国(第94集).mp4
8302992,2010-07-02 19:22:52,00101111100110100100000001010101,世界杯100609热身赛西班牙6-0波兰.mp4
8303630,2010-07-02 19:26:25,00101111100110100100000001010101,全场进攻寥寥无几 C罗任意球成秘密武器.mp4

In [5]:
df_short.loc[df_short['user']=='11011110110011000101100010000010']

,time,user,item
8148432,2010-07-02 15:42:29,11011110110011000101100010000010,波斯王子：时之刃(清晰版).mp4
9290404,2010-07-02 15:42:29,11011110110011000101100010000010,波斯王子：时之刃(清晰版).mp4
8148476,2010-07-02 15:44:14,11011110110011000101100010000010,天才除草人2.mp4
9290448,2010-07-02 15:44:14,11011110110011000101100010000010,天才除草人2.mp4
8148505,2010-07-02 15:45:40,11011110110011000101100010000010,小美女撒谎精(第04集).mp4
9290477,2010-07-02 15:45:40,11011110110011000101100010000010,小美女撒谎精(第04集).mp4
8148511,2010-07-02 15:45:45,11011110110011000101100010000010,都市侠盗第3季(第02集).mp4
8148512,2010-07-02 15:45:45,11011110110011000101100010000010,都市侠盗第3季(第01集).mp4
9290483,2010-07-02 15:45:45,11011110110011000101100010000010,都市侠盗第3季(第02集).mp4
9290484,2010-07-02 15:45:45,11011110110011000101100010000010,都市侠盗第3季(第01集).mp4
8149746,2010-07-02 16:32:47,11011110110011000101100010000010,都市侠盗第3季(第01集).mp4
9291718,2010-07-02 16:32:47,11011110110011000101100010000010,都市侠盗第3季(第01集).mp4

In [6]:
userlist=df_short['user'].drop_duplicates()

In [7]:
userlist=userlist.iloc[::-1]

In [8]:
userlist

8302992    00101111100110100100000001010101
6940217    00101111100110100100010010101101
369144     00111010000100000000000100000010
4619059    00111010000100000000000100000110
4605577    00111010000100000000000100011100
                         ...
8153339    11011110111110011000000000110100
128977     11011110111110011000001101100100
6972493    11011110111110011001000001110111
7140238    11011110111110011001100011000001
4347024    11011110111110011001100100010011
Name: user, Length: 1225506, dtype: object

In [22]:
singleuserdate=df_short.loc[df_short['user']==userlist.iloc[0]]

In [23]:
singleuserdate

,time,user,item
8302992,2010-07-02 19:22:52,00101111100110100100000001010101,世界杯100609热身赛西班牙6-0波兰.mp4
8303630,2010-07-02 19:26:25,00101111100110100100000001010101,全场进攻寥寥无几 C罗任意球成秘密武器.mp4

In [9]:
df_short['time']=pd.to_datetime(df_short['time'])

In [10]:
df_short['interval']=df_short['time'].shift(-1)-df_short['time']

In [17]:
df_cut=df_short.drop(df_short.groupby(['user']).tail(1).index, axis=0)

In [18]:
df_cut

,time,user,item,interval
4347024,2010-06-29 18:44:26,11011110111110011001100100010011,梁静茹豪华婚礼实录.mp4,0 days 00:16:13
4347643,2010-06-29 19:00:39,11011110111110011001100100010011,传奇故事-100125-女研究生自杀之谜.mp4,0 days 00:00:00
4347646,2010-06-29 19:00:39,11011110111110011001100100010011,传奇故事-100125-女研究生自杀之谜.mp4,0 days 00:00:22
4347666,2010-06-29 19:01:01,11011110111110011001100100010011,传奇故事-100126-一场没有骗子的骗局.mp4,0 days 00:00:02
4347667,2010-06-29 19:01:03,11011110111110011001100100010011,传奇故事-100126-一场没有骗子的骗局.mp4,0 days 00:00:02
...,...,...,...,...
6940217,2010-07-01 11:09:50,00101111100110100100010010101101,新三国(第91集).mp4,0 days 00:53:54
6948851,2010-07-01 12:03:44,00101111100110100100010010101101,新三国(第91集).mp4,0 days 00:53:52
6959522,2010-07-01 12:57:36,00101111100110100100010010101101,新三国(第92集).mp4,0 days 01:31:25
7188472,2010-07-01 14:29:01,00101111100110100100010010101101,新三国(第93集).mp4,0 days 01:40:46
8302992,2010-07-02 19:22:52,00101111100110100100000001010101,世界杯100609热身赛西班牙6-0波兰.mp4,0 days 00:03:33

In [19]:
WI=df_cut.drop(df_cut[df_cut['interval']<=timedelta(seconds=0)].index)

In [21]:
WI=WI.drop(WI[WI['interval']>timedelta(hours=2)].index)

In [22]:
WI

,time,user,item,interval
4347024,2010-06-29 18:44:26,11011110111110011001100100010011,梁静茹豪华婚礼实录.mp4,0 days 00:16:13
4347646,2010-06-29 19:00:39,11011110111110011001100100010011,传奇故事-100125-女研究生自杀之谜.mp4,0 days 00:00:22
4347666,2010-06-29 19:01:01,11011110111110011001100100010011,传奇故事-100126-一场没有骗子的骗局.mp4,0 days 00:00:02
4347667,2010-06-29 19:01:03,11011110111110011001100100010011,传奇故事-100126-一场没有骗子的骗局.mp4,0 days 00:00:02
4347670,2010-06-29 19:01:05,11011110111110011001100100010011,传奇故事-100125-女研究生自杀之谜.mp4,0 days 00:29:02
...,...,...,...,...
6940217,2010-07-01 11:09:50,00101111100110100100010010101101,新三国(第91集).mp4,0 days 00:53:54
6948851,2010-07-01 12:03:44,00101111100110100100010010101101,新三国(第91集).mp4,0 days 00:53:52
6959522,2010-07-01 12:57:36,00101111100110100100010010101101,新三国(第92集).mp4,0 days 01:31:25
7188472,2010-07-01 14:29:01,00101111100110100100010010101101,新三国(第93集).mp4,0 days 01:40:46
8302992,2010-07-02 19:22:52,00101111100110100100000001010101,世界杯100609热身赛西班牙6-0波兰.mp4,0 days 00:03:33

In [26]:
b=WI.copy()

In [68]:
b

,time,user,item,interval,agg_value
4347024,2010-06-29 18:44:26,11011110111110011001100100010011,梁静茹豪华婚礼实录.mp4,0 days 00:16:13,0 days 00:16:13
4347646,2010-06-29 19:00:39,11011110111110011001100100010011,传奇故事-100125-女研究生自杀之谜.mp4,0 days 00:00:22,0 days 00:00:22
4347666,2010-06-29 19:01:01,11011110111110011001100100010011,传奇故事-100126-一场没有骗子的骗局.mp4,0 days 00:00:02,0 days 00:00:04
4347667,2010-06-29 19:01:03,11011110111110011001100100010011,传奇故事-100126-一场没有骗子的骗局.mp4,0 days 00:00:02,0 days 00:00:02
4347670,2010-06-29 19:01:05,11011110111110011001100100010011,传奇故事-100125-女研究生自杀之谜.mp4,0 days 00:29:02,0 days 00:51:05
...,...,...,...,...,...
6940217,2010-07-01 11:09:50,00101111100110100100010010101101,新三国(第91集).mp4,0 days 00:53:54,0 days 01:47:46
6948851,2010-07-01 12:03:44,00101111100110100100010010101101,新三国(第91集).mp4,0 days 00:53:52,0 days 00:53:52
6959522,2010-07-01 12:57:36,00101111100110100100010010101101,新三国(第92集).mp4,0 days 01:31:25,0 days 01:31:25
7188472,2010-07-01 14:29:01,00101111100110100100010010101101,新三国(第93集).mp4,0 days 01:40:46,0 days 01:40:46
8302992,2010-07-02 19:22:52,00101111100110100100000001010101,世界杯100609热身赛西班牙6-0波兰.mp4,0 days 00:03:33,0 days 00:03:33

In [73]:
b.drop(b.index[[(1:2)]])

SyntaxError: invalid syntax (Temp/ipykernel_18344/818502401.py, line 1)

In [83]:
10015%10000

1.0015

In [84]:
base=0
i=1
accum=timedelta(seconds=0)
while(i<len(b)):
    while(i<len(b) and WI['item'].iloc[i]==b['item'].iloc[base] and  b['user'].iloc[i]==b['user'].iloc[base]):
        accum+=b['interval'].iloc[i];
        i=i+1;
    if(i==len(b)):
        break
    b.loc[base,'interval']=accum+b.iloc[i]['interval']
    accum=timedelta(seconds=0)
    base=i;
    if(base%10000==0):
        print(base)
    i=base+1;

KeyboardInterrupt:

In [ ]:
while(len(b)!=result_b):
    b['agg_value']=np.where(b['item']==b['item'].shift(-1),b['interval']+b['interval'].shift(-1))
    result_b=b[b['user']!=b['user'].shift(1)]['user','agg_value']

In [40]:
b['agg_value']=np.where(b['item']==b['item'].shift(-1),b['interval']+b['interval'].shift(-1),b['interval'])

In [48]:
result_b

,user,item,agg_value
4696297,11011110111110011001100100010011,传奇故事-100122-那天晚上到底发生了什么.mp4,0 days 00:00:26
6931338,11011110111110011001100011000001,敢死队(第24集).mp4,0 days 00:00:41
9417592,11011110111110011000001101100100,越狱第2季(第14集).mp4,0 days 00:08:49
9424633,11011110111110011000000000110100,大学生了没-100621-他们没钱但很帅.mp4,0 days 00:43:39
126567,11011110110011001111110110111100,天天向上-100625-姜续昌玉米提吴俊余.mp4,0 days 01:22:09
...,...,...,...
8065457,00111010000100000000000100011100,日本AV女星苍井空义卖自拍照为玉树灾区筹款-4月29日.mp4,0 days 00:00:02
4619750,00111010000100000000000100000110,格斗艺术.mp4,0 days 01:17:14
9857524,00111010000100000000000100000010,王牌大贱谍-091110-我再穷都要有一部车.mp4,0 days 00:00:15
7188472,00101111100110100100010010101101,新三国(第93集).mp4,0 days 01:40:46
8302992,00101111100110100100000001010101,世界杯100609热身赛西班牙6-0波兰.mp4,0 days 00:03:33

In [61]:
result_b.loc[result_b['item']=='传奇故事-100125-女研究生自杀之谜.mp4']

,user,item,agg_value
3964744,11011010010101111111101101100100,传奇故事-100125-女研究生自杀之谜.mp4,0 days 00:30:44
4419694,01110011101011011101100000010000,传奇故事-100125-女研究生自杀之谜.mp4,0 days 00:29:48

In [58]:
result_b=b[b['user']!=b['user'].shift(1)][['user','item','agg_value']]

In [46]:
b

,time,user,item,interval,agg_value
4347024,2010-06-29 18:44:26,11011110111110011001100100010011,梁静茹豪华婚礼实录.mp4,0 days 00:16:13,0 days 00:16:13
4347646,2010-06-29 19:00:39,11011110111110011001100100010011,传奇故事-100125-女研究生自杀之谜.mp4,0 days 00:00:22,0 days 00:00:22
4347666,2010-06-29 19:01:01,11011110111110011001100100010011,传奇故事-100126-一场没有骗子的骗局.mp4,0 days 00:00:02,0 days 00:00:04
4347667,2010-06-29 19:01:03,11011110111110011001100100010011,传奇故事-100126-一场没有骗子的骗局.mp4,0 days 00:00:02,0 days 00:00:02
4347670,2010-06-29 19:01:05,11011110111110011001100100010011,传奇故事-100125-女研究生自杀之谜.mp4,0 days 00:29:02,0 days 00:51:05
...,...,...,...,...,...
6940217,2010-07-01 11:09:50,00101111100110100100010010101101,新三国(第91集).mp4,0 days 00:53:54,0 days 01:47:46
6948851,2010-07-01 12:03:44,00101111100110100100010010101101,新三国(第91集).mp4,0 days 00:53:52,0 days 00:53:52
6959522,2010-07-01 12:57:36,00101111100110100100010010101101,新三国(第92集).mp4,0 days 01:31:25,0 days 01:31:25
7188472,2010-07-01 14:29:01,00101111100110100100010010101101,新三国(第93集).mp4,0 days 01:40:46,0 days 01:40:46
8302992,2010-07-02 19:22:52,00101111100110100100000001010101,世界杯100609热身赛西班牙6-0波兰.mp4,0 days 00:03:33,0 days 00:03:33

In [60]:
result_b

,user,item,agg_value
4347024,11011110111110011001100100010011,梁静茹豪华婚礼实录.mp4,0 days 00:16:13
7140238,11011110111110011001100011000001,敢死队(第01集).mp4,0 days 00:00:33
128977,11011110111110011000001101100100,灌篮高手国语版(第01集).mp4,0 days 00:01:50
9424436,11011110111110011000000000110100,活该你单身(预告片).mp4,0 days 00:04:36
126350,11011110110011001111110110111100,天天向上-100625-姜续昌玉米提吴俊余.mp4,0 days 00:07:21
...,...,...,...
4605577,00111010000100000000000100011100,新三国(第86集).mp4,0 days 00:01:55
4619059,00111010000100000000000100000110,人兽杂交.mp4,0 days 00:01:19
369144,00111010000100000000000100000010,火影忍者(第386集).mp4,0 days 00:00:19
6940217,00101111100110100100010010101101,新三国(第91集).mp4,0 days 01:47:46
8302992,00101111100110100100000001010101,世界杯100609热身赛西班牙6-0波兰.mp4,0 days 00:03:33

In [23]:
a=WI.copy()

In [25]:
a.groupby(['item']).max().rename(columns={'interval':'max_interval'})

,time,user,max_interval
item,,,
,2010-07-03 23:58:47,11011110100000111110101010100000,0 days 02:00:00
(21)寻找战士奶爸-08年5月16日 绵竹市汉旺金鱼嘴.mp4,2010-06-28 22:10:05,01110011100101100100010110001011,0 days 00:16:26
(23)寻找从容的李科-08年5月16日 成都凤凰山机场.mp4,2010-06-30 15:56:03,11010011100100001100011010010010,0 days 00:00:23
00100512中道齐家三部曲之二家庭教育(1).mp4,2010-07-03 18:42:09,01111011011110000100100101111010,0 days 00:29:12
00100512中道齐家三部曲之二家庭教育(10).mp4,2010-07-02 12:00:37,01111011011110000100000111000110,0 days 00:51:31
...,...,...,...
龙鸣(第20集).mp4,2010-07-03 15:53:00,11010011011001101010101101101111,0 days 01:50:42
龙鸣(第21集).mp4,2010-06-30 14:17:10,01110100111011101101110010000001,0 days 00:22:48
龙鸣(第22集).mp4,2010-07-02 18:44:30,01110100111011101101110010000001,0 days 01:03:13
龙鸣(第23集).mp4,2010-07-03 20:19:57,11011010010011110111000100001100,0 days 00:46:59
龙鸣(第24集).mp4,2010-07-03 20:22:43,01111100010000010100010111110110,0 days 00:06:55

In [ ]:
interval=[]
for j in range(len(userlist)):
    singleuserdate=df_short.loc[df_short['user']==userlist.iloc[j]];
    i=1
    while(i<len(singleuserdate)):
        interval.append([singleuserdate['time'].iloc[i-1],singleuserdate['user'].iloc[i-1],singleuserdate['item'].iloc[i-1],datetime.strptime(singleuserdate['time'].iloc[i],'%Y-%m-%d %H:%M:%S')-datetime.strptime(singleuserdate['time'].iloc[i-1],'%Y-%m-%d %H:%M:%S')]);
        i=i+1;

In [ ]:
watchinterval=pd.DataFrame(interval,columns=['time','user','item','interval'])

In [ ]:
watchinterval

In [ ]:
WI=watchinterval.copy()

In [ ]:
WI=WI.drop(WI[WI['interval']==timedelta(seconds=0)].index)

In [ ]:
WI=WI.drop(WI[WI['interval']>timedelta(hours=2)].index)

In [ ]:
WI

In [ ]:
##loop for getting the watching time after filtering the inactive action
sumwatchtime=[]
for j in range(len(userlist)):
    singleuserdate=WI.loc[WI['user']==userlist.iloc[j]];
    i=1
    base=0
    accum=timedelta(seconds=0)
    while(i<len(singleuserdate)):
        while(i<len(singleuserdate) and singleuserdate['item'].iloc[i]==singleuserdate['item'].iloc[base]):
            accum+=singleuserdate['interval'].iloc[i];
            i=i+1;
        if(i==len(singleuserdate)):
            break
        sumwatchtime.append([singleuserdate['time'].iloc[base],singleuserdate['user'].iloc[base],singleuserdate['item'].iloc[base],singleuserdate['interval'].iloc[base]+accum]);
        accum=timedelta(seconds=0)
        base=i;
        i=i+1;

In [ ]:
summary=pd.DataFrame(sumwatchtime,columns=['time','user','item','timelength'])

In [ ]:
summary

In [ ]:
sm=summary.copy()

In [ ]:
##sm.groupby('item').apply(lambda t: t[t.timelength==t.timelength.max()])

In [ ]:
sm=sm.groupby(['item'])[['item','timelength']].max()

In [ ]:
sm

In [ ]:
watchratio=summary.copy()

In [ ]:
watchratio['watch ratio']=0 ##add coloum of watch ratio

In [ ]:
for i in range(len(watchratio)):
    watchratio.loc[i,'watch ratio']=watchratio.iloc[i]['timelength']/sm.loc[sm['item']==watchratio.iloc[i]['item'] ].timelength.values[0]
    ##here watchratio.iloc[i]['item'] ].timelength is a pandas Series, so I have to use '.values' to get a one-element Array and '.values[0]' to get a values

In [ ]:
watchratio

In [ ]:
test=watchratio.copy()

In [ ]:
test.drop(test[test['watch ratio']==1].index)

In [ ]:
test2=test.drop(test[test['watch ratio']==1].index)
test2['watch ratio'].plot.hist(bins=50)

In [ ]:
test['watch ratio'].plot.hist(bins=50)

In [ ]:
len(df)